bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/BankIdAttributeProducer.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/config/BankIdConfiguration.java
bankid-idp/bankid-idp-backend/src/main/resources/local/local-metadata.xml

According to https://docs.swedenconnect.se/technical-framework/latest/12_-_BankID_Profile_for_the_Swedish_eID_Framework.html
Fixes #15

Fixed attribute release

---

bankid-idp/bankid-idp-backend/pom.xml
docs/override.md

IS-57 Preparation for overrides of application

---

bankid-idp/bankid-idp-backend/pom.xml
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/audit/AuditEventMapper.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/BankIdAuthenticationController.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/BankIdApiController.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/events/OrderCancellationEvent.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/session/BankIdSessionDataListener.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/config/BankIdConfiguration.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/config/ResilienceConfiguration.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/config/session/InMemorySessionConfiguration.java
bankid-idp/bankid-idp-backend/src/main/resources/application.yml
bankid-idp/bankid-idp-backend/src/test/java/se/swedenconnect/bankid/idp/authn/service/BankIdServiceTest.java
pom.xml

IS-61 Bumped to 1.1.3 of saml-identity-idp

---

bankid-idp/bankid-idp-frontend/src/views/AuthenticateView.vue

Stop polling on error (or completion)

---

bankid-idp/bankid-idp-backend/pom.xml
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/audit/AbstractBankIdAuditEventRepository.java

Will not merge until 1.1.4 is published on Maven central.

Bumped to 1.1.4 of SAML IdP base

---

bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/BankIdApiController.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/ContentOverride.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/CssOverride.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/FrontendOverrideResponse.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/MessageOverride.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/OverrideFileLoader.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/OverrideService.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/package-info.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/config/OverrideConfiguration.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/config/OverrideProperties.java
bankid-idp/bankid-idp-backend/src/main/java/se/swedenconnect/bankid/idp/config/UiProperties.java
bankid-idp/bankid-idp-backend/src/main/resources/application.yml
bankid-idp/bankid-idp-backend/src/main/resources/local/overrides/custom.content
bankid-idp/bankid-idp-backend/src/main/resources/local/overrides/custom.messages
bankid-idp/bankid-idp-frontend/src/main.ts
bankid-idp/bankid-idp-frontend/src/types.ts
docs/bankid-sc-resources.md
docs/configuration.md
docs/development.md
docs/idp-api.md
docs/override.md

@felix-hellman @oestrogen I made some changes to `MessageOverride` that was hardwired to only handle Swedish and English. We need to fix the front-end for this ...

Changes concerning overrides

---

bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/BankIdConfiguration.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/InMemorySessionConfiguration.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.java
bankid-idp/src/main/resources/META-INF/additional-spring-configuration-metadata.json
docs/configuration.md
docs/development.md

IS-64 Configure TTL for replay checker

---

docs/configuration.md
docs/override.md

IS-109 Documented how to extend session handling

---

bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/BankIdConfiguration.java
bankid-idp/src/main/resources/application.yml
docs/configuration.md
docs/monitoring.md

Also added documentation about how to set up actuator in Quarkus-style ...
Closes #106

IS-106 Dynamic way of securing actuator-endpoints

---

bankid-api/src/main/java/se/swedenconnect/bankid/rpapi/service/impl/BankIDClientImpl.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/session/BankIdSessionDataListener.java

IS-99 Logging of collect-operations should be done on debug-level

---

bankid-api/src/main/java/se/swedenconnect/bankid/rpapi/support/WebClientFactoryBean.java
docs/configuration.md

IS-112 Enabled the use of HTTP proxy

---

bankid-idp/src/main/frontend/src/components/BankIdLogo.vue
bankid-idp/src/main/frontend/src/views/AuthenticateView.vue
bankid-idp/src/main/frontend/src/views/DeviceSelectView.vue

Move BankID logo to bottom of main content box

---

docs/configuration.md
docs/index.md
docs/join-sweden-connect.md

IS-126 Information about how to join Sweden Connect

---

bankid-idp/env/local/developer.yml
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/FrontendController.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/api/BankIdApiController.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/api/UiInformationProvider.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/api/overrides/OverrideService.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/BankIdConfiguration.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/OverrideProperties.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/UiProperties.java
bankid-idp/src/main/resources/static/images/transparent.svg
docs/configuration.md
docs/override.md
samples/sandbox/config/logo-notext.svg
samples/sandbox/config/sandbox.yml

Must be set. Otherwise an invisible SVG is loaded.
Closes #131

IS-131 Logotype in footer is now optional.

---

bankid-idp/env/local/developer.yml
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/api/BankIdApiController.java
bankid-idp/src/main/resources/application.yml

IS-146 Fixed bad log level

---

bankid-frontend/src/components/QrDisplay.vue

It is now 200x200 which should be more suitable ...
Closes #149

IS-149 Smaller QR code

---

bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/api/SelectedDeviceInformation.java

Removes duplicated field in SelectedDeviceInformation

---

bankid-frontend/package.json
bankid-frontend/pom.xml

Maven will run tests for frontend when building

---

bankid-idp/pom.xml

IS-160 fixed dependencies

---

bankid-frontend/src/views/DeviceSelectView.vue

IS-175: Make sure device data is loaded before loading device select component

---

bankid-frontend/src/main.ts
bankid-idp/env/local/overrides/custom.messages
samples/dynamic-overrides/services/overrides/custom.messages

IS-180: Refactor message overriding

---

bankid-frontend/src/views/AutoStartView.vue

Clears variables for hiding autostart component and resets token on api cancel

Autostarts when retry button is pressed

---

bankid-frontend/src/components/QrModal.vue

IS-196: Only stop polling if QR code is showing when closing modal

---

bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/service/BankIdService.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/session/BankIdSessionData.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/session/BankIdSessionDataListener.java
bankid-idp/src/test/java/se/swedenconnect/bankid/idp/authn/service/BankIdResponseFixture.java
bankid-idp/src/test/java/se/swedenconnect/bankid/idp/integration/BankIdIdpIT.java

Provides StatusCodeFactory status about QR display from api rather than from session

---

bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/session/BankIdSessionData.java
bankid-idp/src/test/java/se/swedenconnect/bankid/idp/integration/BankIdIdpIT.java
bankid-idp/src/test/java/se/swedenconnect/bankid/idp/integration/client/FrontendClient.java

Bases previous device selection on completion device rather than init device

---

bankid-api/pom.xml
bankid-api/src/main/java/se/swedenconnect/bankid/rpapi/LibraryVersion.java
bankid-frontend/pom.xml
bankid-idp/pom.xml
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/ApplicationVersion.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/api/UiInformationProvider.java
bankid-idp/src/main/resources/application.yml
pom.xml

IS-206 Protect bad config from leading to NPE

---

bankid-frontend/src/App.vue
bankid-frontend/src/Service.ts
bankid-frontend/src/locale/messages.json
bankid-idp/env/local/metadata/local-metadata.xml
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/error/ApiControllerAdvice.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/authn/error/UserErrorFactory.java
docs/override.md

Adds error mapping for NoSuchRelyingPartyException + handles api errors in frontend for /api/ui

---

bankid-api/pom.xml
bankid-api/src/main/java/se/swedenconnect/bankid/rpapi/LibraryVersion.java
bankid-frontend/pom.xml
bankid-idp/pom.xml
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/ApplicationVersion.java
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedissonAddressCustomizers.java
bankid-idp/src/test/java/se/swedenconnect/bankid/idp/ApplicationVersionTest.java
pom.xml

Application can start without NAT translation table proeprty

---

bankid-idp/pom.xml
pom.xml

By updating dependencies
Closes #219

IS-219 Fix md signing key bug

---

bankid-idp/env/local/developer.yml
bankid-idp/src/test/resources/application.yml
docs/configuration.md
samples/external-frontend/bankid-config/externalized-frontend.yml
samples/sandbox/config/sandbox.yml

Fix syntax error for text format

---

bankid-idp/src/main/resources/application.yml

IS-233 Corrected wrong size for image width

---

bankid-idp/pom.xml

Remove exposed ports for bankididp

---

bankid-frontend/package-lock.json
bankid-frontend/package.json
bankid-frontend/src/AutoStartLinkFactory.ts
bankid-frontend/src/views/AutoStartView.vue

Update NPM packages and dependencies

---

.github/workflows/build-docker.yml
.github/workflows/review.yml
bankid-idp/src/main/java/se/swedenconnect/bankid/idp/health/SamlMetadataHealthIndicator.java
bankid-idp/src/test/resources/application.yml
pom.xml

* Update credential configuration for test suite

Enables integration tests in maven

---

bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/BankIdConfiguration.java
docs/release-notes.md

IS-301 Permit all for actuator endpoints
